package com.wasitech.permissioncenter.java.com.wasitech.ai.word;

public class Cs {
    public static boolean cage(String str){return str.contains("cage");}
    public static boolean cake(String str){return str.contains("cake");}
    public static boolean calculate(String str){return str.contains("calculate");}
    public static boolean calculation(String str){return str.contains("calculation");}
    public static boolean calendar(String str){return str.contains("calendar");}
    public static boolean calf(String str){return str.contains("calf");}
    public static boolean call(String str){return str.contains("call");}
    public static boolean callous(String str){return str.contains("callous");}
    public static boolean calm(String str){return str.contains("calm");}
    public static boolean camera(String str){return str.contains("camera");}
    public static boolean camp(String str){return str.contains("camp");}
    public static boolean campaign(String str){return str.contains("campaign");}
    public static boolean campus(String str){return str.contains("campus");}
    public static boolean can(String str){return str.contains("can");}
    public static boolean cancel(String str){return str.contains("cancel");}
    public static boolean cancer(String str){return str.contains("cancer");}
    public static boolean candid(String str){return str.contains("candid");}
    public static boolean candidate(String str){return str.contains("candidate");}
    public static boolean candy(String str){return str.contains("candy");}
    public static boolean cap(String str){return str.contains("cap");}
    public static boolean capable(String str){return str.contains("capable");}
    public static boolean capacity(String str){return str.contains("capacity");}
    public static boolean capital(String str){return str.contains("capital");}
    public static boolean captain(String str){return str.contains("captain");}
    public static boolean capture(String str){return str.contains("capture");}
    public static boolean car(String str){return str.contains("car");}
    public static boolean carbon(String str){return str.contains("carbon");}
    public static boolean carcinogen(String str){return str.contains("carcinogen");}
    public static boolean card(String str){return str.contains("card");}
    public static boolean care(String str){return str.contains("care");}
    public static boolean career(String str){return str.contains("career");}
    public static boolean careful(String str){return str.contains("careful");}
    public static boolean careless(String str){return str.contains("careless");}
    public static boolean carpenter(String str){return str.contains("carpenter");}
    public static boolean carpet(String str){return str.contains("carpet");}
    public static boolean carrot(String str){return str.contains("carrot");}
    public static boolean carry(String str){return str.contains("carry");}
    public static boolean casE(String str){return str.contains("case");}
    public static boolean cash(String str){return str.contains("cash");}
    public static boolean cashier(String str){return str.contains("cashier");}
    public static boolean cast(String str){return str.contains("cast");}
    public static boolean castle(String str){return str.contains("castle");}
    public static boolean cat(String str){return str.contains("cat");}
    public static boolean catalog(String str){return str.contains("catalog");}
    public static boolean catcH(String str){return str.contains("catch");}
    public static boolean catcher(String str){return str.contains("catcher");}
    public static boolean category(String str){return str.contains("category");}
    public static boolean cattle(String str){return str.contains("cattle");}
    public static boolean cause(String str){return str.contains("cause");}
    public static boolean caution(String str){return str.contains("caution");}
    public static boolean cautious(String str){return str.contains("cautious");}
    public static boolean cave(String str){return str.contains("cave");}
    public static boolean cease(String str){return str.contains("cease");}
    public static boolean ceiling(String str){return str.contains("ceiling");}
    public static boolean celebrate(String str){return str.contains("celebrate");}
    public static boolean celebration(String str){return str.contains("celebration");}
    public static boolean cell(String str){return str.contains("cell");}
    public static boolean cent(String str){return str.contains("cent");}
    public static boolean center(String str){return str.contains("center");}
    public static boolean central(String str){return str.contains("central");}
    public static boolean century(String str){return str.contains("century");}
    public static boolean ceremony(String str){return str.contains("ceremony");}
    public static boolean certain(String str){return str.contains("certain");}
    public static boolean certainly(String str){return str.contains("certainly");}
    public static boolean certainty(String str){return str.contains("certainty");}
    public static boolean chain(String str){return str.contains("chain");}
    public static boolean chair(String str){return str.contains("chair");}
    public static boolean challenge(String str){return str.contains("challenge");}
    public static boolean chamber(String str){return str.contains("chamber");}
    public static boolean champion(String str){return str.contains("champion");}
    public static boolean championship(String str){return str.contains("championship");}
    public static boolean chance(String str){return str.contains("chance");}
    public static boolean change(String str){return str.contains("change");}
    public static boolean channel(String str){return str.contains("channel");}
    public static boolean chaos(String str){return str.contains("chaos");}
    public static boolean chapter(String str){return str.contains("chapter");}
    public static boolean character(String str){return str.contains("character");}
    public static boolean characteristic(String str){return str.contains("characteristic");}
    public static boolean charge(String str){return str.contains("charge");}
    public static boolean charity(String str){return str.contains("charity");}
    public static boolean charm(String str){return str.contains("charm");}
    public static boolean charming(String str){return str.contains("charming");}
    public static boolean chart(String str){return str.contains("chart");}
    public static boolean chase(String str){return str.contains("chase");}
    public static boolean chat(String str){return str.contains("chat");}
    public static boolean cheap(String str){return str.contains("cheap");}
    public static boolean cheat(String str){return str.contains("cheat");}
    public static boolean check(String str){return str.contains("check");}
    public static boolean cheek(String str){return str.contains("cheek");}
    public static boolean cheerful(String str){return str.contains("cheerful");}
    public static boolean cheese(String str){return str.contains("cheese");}
    public static boolean chef(String str){return str.contains("chef");}
    public static boolean chemical(String str){return str.contains("chemical");}
    public static boolean chemistry(String str){return str.contains("chemistry");}
    public static boolean chest(String str){return str.contains("chest");}
    public static boolean chew(String str){return str.contains("chew");}
    public static boolean chicken(String str){return str.contains("chicken");}
    public static boolean chief(String str){return str.contains("chief");}
    public static boolean child(String str){return str.contains("child");}
    public static boolean childhood(String str){return str.contains("childhood");}
    public static boolean children(String str){return str.contains("children");}
    public static boolean chilly(String str){return str.contains("chilly");}
    public static boolean chin(String str){return str.contains("chin");}
    public static boolean chip(String str){return str.contains("chip");}
    public static boolean chocolate(String str){return str.contains("chocolate");}
    public static boolean choice(String str){return str.contains("choice");}
    public static boolean choke(String str){return str.contains("choke");}
    public static boolean choose(String str){return str.contains("choose");}
    public static boolean chop(String str){return str.contains("chop");}
    public static boolean Christmas(String str){return str.contains("Christmas");}
    public static boolean church(String str){return str.contains("church");}
    public static boolean circle(String str){return str.contains("circle");}
    public static boolean circumspect(String str){return str.contains("circumspect");}
    public static boolean circumstance(String str){return str.contains("circumstance");}
    public static boolean circumvent(String str){return str.contains("circumvent");}
    public static boolean citation(String str){return str.contains("citation");}
    public static boolean citizen(String str){return str.contains("citizen");}
    public static boolean city(String str){return str.contains("city");}
    public static boolean civil(String str){return str.contains("civil");}
    public static boolean claim(String str){return str.contains("claim");}
    public static boolean clap(String str){return str.contains("clap");}
    public static boolean clarify(String str){return str.contains("clarify");}
    public static boolean clasS(String str){return str.contains("class");}
    public static boolean classic(String str){return str.contains("classic");}
    public static boolean cloud(String str){return str.contains("cloud");}
    public static boolean cloudy(String str){return str.contains("cloudy");}
    public static boolean club(String str){return str.contains("club");}
    public static boolean coach(String str){return str.contains("coach");}
    public static boolean coal(String str){return str.contains("coal");}
    public static boolean coalesce(String str){return str.contains("coalesce");}
    public static boolean coast(String str){return str.contains("coast");}
    public static boolean coat(String str){return str.contains("coat");}
    public static boolean cockpit(String str){return str.contains("cockpit");}
    public static boolean code(String str){return str.contains("code");}
    public static boolean coffee(String str){return str.contains("coffee");}
    public static boolean cogent(String str){return str.contains("cogent");}
    public static boolean coherent(String str){return str.contains("coherent");}
    public static boolean coin(String str){return str.contains("coin");}
    public static boolean cold(String str){return str.contains("cold");}
    public static boolean collapse(String str){return str.contains("collapse");}
    public static boolean collar(String str){return str.contains("collar");}
    public static boolean collect(String str){return str.contains("collect");}
    public static boolean collection(String str){return str.contains("collection");}
    public static boolean college(String str){return str.contains("college");}
    public static boolean color(String str){return str.contains("color");}
    public static boolean column(String str){return str.contains("column");}
    public static boolean comb(String str){return str.contains("comb");}
    public static boolean combination(String str){return str.contains("combination");}
    public static boolean combine(String str){return str.contains("combine");}
    public static boolean come(String str){return str.contains("come");}
    public static boolean comedy(String str){return str.contains("comedy");}
    public static boolean comfort(String str){return str.contains("comfort");}
    public static boolean comfortable(String str){return str.contains("comfortable");}
    public static boolean command(String str){return str.contains("command");}
    public static boolean comment(String str){return str.contains("comment");}
    public static boolean commercial(String str){return str.contains("commercial");}
    public static boolean commission(String str){return str.contains("commission");}
    public static boolean commit(String str){return str.contains("commit");}
    public static boolean committee(String str){return str.contains("committee");}
    public static boolean common(String str){return str.contains("common");}
    public static boolean commonLaw(String str){return str.contains("common-law");}
    public static boolean communicate(String str){return str.contains("communicate");}
    public static boolean communication(String str){return str.contains("communication");}
    public static boolean community(String str){return str.contains("community");}
    public static boolean commute(String str){return str.contains("commute");}
    public static boolean company(String str){return str.contains("company");}
    public static boolean compare(String str){return str.contains("compare");}
    public static boolean comparison(String str){return str.contains("comparison");}
    public static boolean compassion(String str){return str.contains("compassion");}
    public static boolean compete(String str){return str.contains("compete");}
    public static boolean competition(String str){return str.contains("competition");}
    public static boolean competitive(String str){return str.contains("competitive");}
    public static boolean complain(String str){return str.contains("complain");}
    public static boolean complaint(String str){return str.contains("complaint");}
    public static boolean complete(String str){return str.contains("complete");}
    public static boolean completion(String str){return str.contains("completion");}
    public static boolean complex(String str){return str.contains("complex");}
    public static boolean complicate(String str){return str.contains("complicate");}
    public static boolean complicated(String str){return str.contains("complicated");}
    public static boolean component(String str){return str.contains("component");}
    public static boolean compose(String str){return str.contains("compose");}
    public static boolean composition(String str){return str.contains("composition");}
    public static boolean compost(String str){return str.contains("compost");}
    public static boolean compound(String str){return str.contains("compound");}
    public static boolean comprehensive(String str){return str.contains("comprehensive");}
    public static boolean compulsive(String str){return str.contains("compulsive");}
    public static boolean computer(String str){return str.contains("computer");}
    public static boolean concentrate(String str){return str.contains("concentrate");}
    public static boolean concentration(String str){return str.contains("concentration");}
    public static boolean concept(String str){return str.contains("concept");}
    public static boolean concern(String str){return str.contains("concern");}
    public static boolean concert(String str){return str.contains("concert");}
    public static boolean conclude(String str){return str.contains("conclude");}
    public static boolean conclusion(String str){return str.contains("conclusion");}
    public static boolean concrete(String str){return str.contains("concrete");}
    public static boolean condition(String str){return str.contains("condition");}
    public static boolean conduct(String str){return str.contains("conduct");}
    public static boolean conference(String str){return str.contains("conference");}
    public static boolean confidence(String str){return str.contains("confidence");}
    public static boolean confident(String str){return str.contains("confident");}
    public static boolean confine(String str){return str.contains("confine");}
    public static boolean confirm(String str){return str.contains("confirm");}
    public static boolean conflict(String str){return str.contains("conflict");}
    public static boolean confuse(String str){return str.contains("confuse");}
    public static boolean confusion(String str){return str.contains("confusion");}
    public static boolean congress(String str){return str.contains("congress");}
    public static boolean conjunction(String str){return str.contains("conjunction");}
    public static boolean connect(String str){return str.contains("connect");}
    public static boolean connection(String str){return str.contains("connection");}
    public static boolean conscience(String str){return str.contains("conscience");}
    public static boolean conscious(String str){return str.contains("conscious");}
    public static boolean consent(String str){return str.contains("consent");}
    public static boolean conservation(String str){return str.contains("conservation");}
    public static boolean conservationist(String str){return str.contains("conservationist");}
    public static boolean conservative(String str){return str.contains("conservative");}
    public static boolean consider(String str){return str.contains("consider");}
    public static boolean considerable(String str){return str.contains("considerable");}
    public static boolean consideration(String str){return str.contains("consideration");}
    public static boolean consist(String str){return str.contains("consist");}
    public static boolean consistent(String str){return str.contains("consistent");}
    public static boolean constant(String str){return str.contains("constant");}
    public static boolean constantly(String str){return str.contains("constantly");}
    public static boolean constitution(String str){return str.contains("constitution");}
    public static boolean construct(String str){return str.contains("construct");}
    public static boolean construction(String str){return str.contains("construction");}
    public static boolean construe(String str){return str.contains("construe");}
    public static boolean consult(String str){return str.contains("consult");}
    public static boolean consumer(String str){return str.contains("consumer");}
    public static boolean contact(String str){return str.contains("contact");}
    public static boolean contagious(String str){return str.contains("contagious");}
    public static boolean contain(String str){return str.contains("contain");}
    public static boolean container(String str){return str.contains("container");}
    public static boolean contaminant(String str){return str.contains("contaminant");}
    public static boolean contamination(String str){return str.contains("contamination");}
    public static boolean contemporary(String str){return str.contains("contemporary");}
    public static boolean content(String str){return str.contains("content");}
    public static boolean contentment(String str){return str.contains("contentment");}
    public static boolean contest(String str){return str.contains("contest");}
    public static boolean context(String str){return str.contains("context");}
    public static boolean continent(String str){return str.contains("continent");}
    public static boolean continually(String str){return str.contains("continually");}
    public static boolean continuE(String str){return str.contains("continue");}
    public static boolean continuous(String str){return str.contains("continuous");}
    public static boolean continuously(String str){return str.contains("continuously");}
    public static boolean contract(String str){return str.contains("contract");}
    public static boolean contrast(String str){return str.contains("contrast");}
    public static boolean contribute(String str){return str.contains("contribute");}
    public static boolean contribution(String str){return str.contains("contribution");}
    public static boolean control(String str){return str.contains("control");}
    public static boolean convenient(String str){return str.contains("convenient");}
    public static boolean conversation(String str){return str.contains("conversation");}
    public static boolean convert(String str){return str.contains("convert");}
    public static boolean convince(String str){return str.contains("convince");}
    public static boolean cook(String str){return str.contains("cook");}
    public static boolean cookie(String str){return str.contains("cookie");}
    public static boolean cool(String str){return str.contains("cool");}
    public static boolean cooperate(String str){return str.contains("cooperate");}
    public static boolean cooperation(String str){return str.contains("cooperation");}
    public static boolean cope(String str){return str.contains("cope");}
    public static boolean copious(String str){return str.contains("copious");}
    public static boolean copy(String str){return str.contains("copy");}
    public static boolean copyright(String str){return str.contains("copyright");}
    public static boolean core(String str){return str.contains("core");}
    public static boolean corn(String str){return str.contains("corn");}
    public static boolean corner(String str){return str.contains("corner");}
    public static boolean corporate(String str){return str.contains("corporate");}
    public static boolean corporation(String str){return str.contains("corporation");}
    public static boolean corpulent(String str){return str.contains("corpulent");}
    public static boolean correct(String str){return str.contains("correct");}
    public static boolean correspond(String str){return str.contains("correspond");}
    public static boolean cost(String str){return str.contains("cost");}
    public static boolean cottage(String str){return str.contains("cottage");}
    public static boolean cotton(String str){return str.contains("cotton");}
    public static boolean cough(String str){return str.contains("cough");}
    public static boolean could(String str){return str.contains("could");}
    public static boolean council(String str){return str.contains("council");}
    public static boolean count(String str){return str.contains("count");}
    public static boolean country(String str){return str.contains("country");}
    public static boolean couple(String str){return str.contains("couple");}
    public static boolean courage(String str){return str.contains("courage");}
    public static boolean courageous(String str){return str.contains("courageous");}
    public static boolean course(String str){return str.contains("course");}
    public static boolean court(String str){return str.contains("court");}
    public static boolean cousin(String str){return str.contains("cousin");}
    public static boolean cover(String str){return str.contains("cover");}
    public static boolean cow(String str){return str.contains("cow");}
    public static boolean cowardly(String str){return str.contains("cowardly");}
    public static boolean crack(String str){return str.contains("crack");}
    public static boolean craft(String str){return str.contains("craft");}
    public static boolean crash(String str){return str.contains("crash");}
    public static boolean crazy(String str){return str.contains("crazy");}
    public static boolean cream(String str){return str.contains("cream");}
    public static boolean create(String str){return str.contains("create");}
    public static boolean creative(String str){return str.contains("creative");}
    public static boolean creature(String str){return str.contains("creature");}
    public static boolean credence(String str){return str.contains("credence");}
    public static boolean credible(String str){return str.contains("credible");}
    public static boolean credit(String str){return str.contains("credit");}
    public static boolean crew(String str){return str.contains("crew");}
    public static boolean crime(String str){return str.contains("crime");}
    public static boolean criminal(String str){return str.contains("criminal");}
    public static boolean crisis(String str){return str.contains("crisis");}
    public static boolean crisp(String str){return str.contains("crisp");}
    public static boolean cruel(String str){return str.contains("cruel");}
    public static boolean crutch(String str){return str.contains("crutch");}
    public static boolean curiosity(String str){return str.contains("curiosity");}
    public static boolean currency(String str){return str.contains("currency");}
    public static boolean custody(String str){return str.contains("custody");}
    public static boolean customs(String str){return str.contains("customs");}
    public static boolean cut(String str){return str.contains("cut");}
    public static boolean cynical(String str){return str.contains("cynical");}

}
